import type { Metadata } from "next";
import "./globals.css";
import RelayProvider from "./lib/RelayProvider";
import { Suspense } from "react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
         <Suspense
                fallback={
                  <div className="text-center p-10 text-xl font-semibold">
                    Loading ...
                  </div>
                }
              >
        <RelayProvider>
        {children}
        </RelayProvider>
        </Suspense>
      </body>
    </html>
  );
}
